name: r_dart_library
description: A core library of R.dart
homepage: 'https://github.com/YK-Unit/r_dart_library'
version: 1.0.0
environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
